use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GraniteMoeHybridConfig {
    pub vocab_size: usize,
    pub hidden_size: usize,
    pub intermediate_size: usize,
    pub num_hidden_layers: usize,
    pub num_attention_heads: usize,
    pub num_key_value_heads: Option<usize>,
    pub hidden_act: String,
    pub max_position_embeddings: usize,
    pub initializer_range: f64,
    pub rms_norm_eps: f64,
    pub use_cache: bool,
    pub pad_token_id: Option<usize>,
    pub bos_token_id: Option<usize>,
    pub eos_token_id: Option<serde_json::Value>,
    pub tie_word_embeddings: bool,
    pub rope_parameters: Option<serde_json::Value>, 
    pub attention_bias: bool,
    pub attention_dropout: f64,
    pub embedding_multiplier: f64,
    pub logits_scaling: f64,
    pub residual_multiplier: f64,
    pub attention_multiplier: f64,
    pub num_local_experts: Option<usize>,
    pub num_experts_per_tok: Option<usize>,
    pub output_router_logits: Option<bool>,
    pub router_aux_loss_coef: Option<f64>,
    pub shared_intermediate_size: usize,
    pub position_embedding_type: Option<String>,
    pub layer_types: Option<Vec<String>>,
    pub mamba_n_heads: Option<usize>,
    pub mamba_n_groups: Option<usize>,
    pub mamba_d_state: Option<usize>,
    pub mamba_d_head: Option<serde_json::Value>, 
    pub mamba_d_conv: Option<usize>,
    pub mamba_expand: Option<usize>,
    pub mamba_chunk_size: Option<usize>,
    pub mamba_conv_bias: Option<bool>,
    pub mamba_proj_bias: Option<bool>,
    pub time_step_min: Option<f64>,
    pub time_step_max: Option<f64>,
    pub time_step_limit: Option<(f64, f64)>,
}

impl Default for GraniteMoeHybridConfig {
    fn default() -> Self {
        Self {
            vocab_size: 32000,
            hidden_size: 4096,
            intermediate_size: 11008,
            num_hidden_layers: 32,
            num_attention_heads: 32,
            num_key_value_heads: None,
            hidden_act: "silu".to_string(),
            max_position_embeddings: 2048,
            initializer_range: 0.02,
            rms_norm_eps: 1e-6,
            use_cache: true,
            pad_token_id: None,
            bos_token_id: Some(1),
            eos_token_id: Some(serde_json::json!([2])),
            tie_word_embeddings: false,
            rope_parameters: None,
            attention_bias: false,
            attention_dropout: 0.0,
            embedding_multiplier: 1.0,
            logits_scaling: 1.0,
            residual_multiplier: 1.0,
            attention_multiplier: 1.0,
            num_local_experts: Some(8),
            num_experts_per_tok: Some(2),
            output_router_logits: Some(false),
            router_aux_loss_coef: Some(0.001),
            shared_intermediate_size: 1024,
            position_embedding_type: None,
            layer_types: None,
            mamba_n_heads: Some(128),
            mamba_n_groups: Some(1),
            mamba_d_state: Some(256),
            mamba_d_head: Some(serde_json::json!("auto")),
            mamba_d_conv: Some(4),
            mamba_expand: Some(2),
            mamba_chunk_size: Some(256),
            mamba_conv_bias: Some(true),
            mamba_proj_bias: Some(false),
            time_step_min: Some(0.001),
            time_step_max: Some(0.1),
            time_step_limit: Some((0.0, f64::INFINITY)),
        }
    }
}