[package]
name = "attention_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "attention_rs"
path = "mod.rs"

[dependencies]
candle-core = { git = "https://github.com/guoqingbao/candle.git", version = "0.8.3", rev = "5bed038" }
candle-nn = { git = "https://github.com/guoqingbao/candle.git", version = "0.8.3", rev = "5bed038" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
parking_lot = "0.12"
anyhow = "1.0"
half = "2.7.1"
bytemuck = "1.25.0"
libc = "0.2"
tracing = "0.1.44"
rayon = "1.10"
kernels = { path = "kernels" }

[features]
default = ["cuda"]
cuda = ["candle-core/cuda", "candle-nn/cuda"]
metal = ["candle-core/metal", "candle-nn/metal"]
